const http=require('http');const fs=require('fs');const path=require('path');const crypto=require('crypto');
const PORT=process.env.PORT||8080;const KEY=process.env.SINRUTINA_KEY||'';const STATE='/tmp/sinrutina-state.json';
let state={tasks:[],deleted:[],updatedAt:null};try{state=JSON.parse(fs.readFileSync(STATE,'utf8'))}catch{}
const save=()=>{state.updatedAt=new Date().toISOString();try{fs.writeFileSync(STATE,JSON.stringify(state))}catch{}};
const json=(res,status,data)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type, X-SinRutina-Key, X-SinRutina-Device','Access-Control-Allow-Methods':'GET,POST,OPTIONS'});res.end(JSON.stringify(data))};
const body=req=>new Promise((ok,bad)=>{let s='';req.on('data',d=>{s+=d;if(s.length>2e6)req.destroy()});req.on('end',()=>{try{ok(s?JSON.parse(s):{})}catch(e){bad(e)}});req.on('error',bad)});
const auth=req=>KEY&&req.headers['x-sinrutina-key']===KEY;
const estimate=text=>{text=String(text||'').toLowerCase();let template=/correo|email|mail/.test(text)?'email':/comprar|retirar|pagar/.test(text)?'errand':/cita|reunión|reunion|hora|dentista/.test(text)?'appointment':/whatsapp|mensaje/.test(text)?'message':/decidir|elegir|comparar/.test(text)?'decision':/pdf|documento|informe|archivo/.test(text)?'document':'general';let base={email:12,appointment:15,errand:25,document:30,decision:20,message:6,general:15}[template];return{minutes:Math.ceil(base/5)*5,template,priority:/hoy|urgente|ahora|vence/.test(text)?'high':'normal',bucket:/esperando|a la espera|depende de/.test(text)?'waiting':/leer|revisar/.test(text)?'read':/hoy|urgente|ahora|vence/.test(text)?'now':'later',reason:'Estimación local del puente SinRutina',engine:'local-api'}};
const newTask=(title,extra={})=>{const e=estimate(title);return{id:'api-'+crypto.randomUUID(),title:String(title||'Tarea').trim(),duration:e.minutes,template:e.template,bucket:e.bucket,priority:e.priority,source:'api',note:'',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),...extra}};
const nextTask=()=>{const rank={high:0,normal:1,low:2};return state.tasks.filter(t=>!['done','someday'].includes(t.bucket)).sort((a,b)=>(a.bucket==='now'?-10:0)-(b.bucket==='now'?-10:0)||(rank[a.priority]??1)-(rank[b.priority]??1)||String(a.createdAt||'').localeCompare(String(b.createdAt||'')))[0]||null};
const serve=(req,res)=>{let p=decodeURIComponent(new URL(req.url,'http://x').pathname);if(p==='/')p='/index.html';const f=path.join(process.cwd(),p.replace(/^\/+/,''));if(!f.startsWith(process.cwd()))return res.writeHead(403).end();fs.readFile(f,(e,d)=>{if(e)return res.writeHead(404,{'Content-Type':'text/plain'}).end('Not found');const ext=path.extname(f);const ct={'.html':'text/html; charset=utf-8','.js':'application/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.svg':'image/svg+xml'}[ext]||'application/octet-stream';res.writeHead(200,{'Content-Type':ct,'Cache-Control':ext==='.html'?'no-cache':'public, max-age=3600'});res.end(d)})};
http.createServer(async(req,res)=>{const u=new URL(req.url,'http://x');if(req.method==='OPTIONS')return json(res,204,{});if(!u.pathname.startsWith('/api/'))return serve(req,res);if(u.pathname==='/api/health')return json(res,200,{ok:true,service:'SinRutina API'});if(!auth(req))return json(res,401,{error:'unauthorized'});try{
if(req.method==='GET'&&u.pathname==='/api/shortcut/tasks/next')return json(res,200,{task:nextTask()});
if(req.method==='POST'&&u.pathname==='/api/tasks/sync'){const b=await body(req);if(Array.isArray(b.tasks))state.tasks=b.tasks;if(Array.isArray(b.deleted))state.deleted=b.deleted;save();return json(res,200,{tasks:state.tasks,deleted:state.deleted,updatedAt:state.updatedAt})}
if(req.method==='POST'&&u.pathname==='/api/shortcut/tasks/natural'){const b=await body(req),t=newTask(b.text);state.tasks.unshift(t);save();return json(res,200,{task:t})}
if(req.method==='POST'&&u.pathname==='/api/shortcut/mail/capture'){const b=await body(req),title=b.subject?`Responder: ${b.subject}`:(b.sender?`Responder a ${b.sender}`:'Revisar correo'),t=newTask(title,{template:'email',note:[b.sender,b.preview].filter(Boolean).join(' · ')});state.tasks.unshift(t);save();return json(res,200,{task:t})}
if(req.method==='POST'&&u.pathname==='/api/shortcut/sync'){const b=await body(req),items=Array.isArray(b.items)?b.items:[];for(const x of items){if(x.completed)continue;const marker=`${b.source||'external'}:${x.externalId||x.id||x.title}`;if(!state.tasks.some(t=>t.externalMarker===marker)){state.tasks.push(newTask(x.title||'Tarea',{externalMarker:marker,note:x.notes||'',dueAt:x.dueAt||null}))}}save();return json(res,200,{outgoing:[],cursor:state.updatedAt,tasks:state.tasks})}
if(req.method==='POST'&&u.pathname==='/api/estimate-duration'){const b=await body(req);return json(res,200,estimate(b.title||b.text||''))}
if(req.method==='POST'&&u.pathname==='/api/assist'){return json(res,200,{engine:'local-api',result:{text:'',title:'',subject:''}})}
return json(res,404,{error:'not_found'})}catch(e){return json(res,400,{error:'bad_request'})}}).listen(PORT,'0.0.0.0',()=>console.log('SinRutina listening on',PORT));
